on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  main:
    strategy:

      fail-fast: false # Don't stop all the workflows when one of them fails.

      matrix:
        os: [ubuntu-latest, macos-latest] # List of GitHuh Actions platform to run the workflow on

    runs-on: ${{ matrix.os }} # Run the continous integration workflow on each OS listed in the matrix.

    steps:
        # Check-out the repository
      - uses: actions/checkout@v2

        # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v1
        with:
          version: 1.2.0-rc1

        # Build the project using the validation build profile to enforce static analysis and coding style.
      #- run: alr build --validation
      - run: alr build

      - run: cd tests && alr build

        # Run the instrumented testsuite. This will produce at least one `.srctrace` file for the coverage analysis.
      - run: cd tests && alr exec ./bin/tests
